minimum_pre_commit_version: 3.3.0
default_install_hook_types: [pre-commit, commit-msg]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md] # Do not process Markdown files.
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-toml

  - repo: https://github.com/PyCQA/flake8
    rev: "7.3.0"
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies:
          [
            "git+https://github.com/RedHatQE/flake8-plugins.git@v0.0.6",
            "flake8-mutable",
          ]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: .*/__snapshots__/.*|.*-input\.json$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
      - id: ruff-format

  # https://github.com/renovatebot/pre-commit-hooks/issues/2621
  # This hook goes over the 250MiB limit that pre-commit.ci imposes
  # Disable unless a solution is found.
  # - repo: https://github.com/renovatebot/pre-commit-hooks
  #   rev: 39.45.0
  #   hooks:
  #     - id: renovate-config-validator

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML", "types-requests"]
        exclude: ^(docs/|.*test.*\.py$|utilities/manifests/.*|utilities/plugins/tgis_grpc/.*)


  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [ commit-msg ]
        args:
          - --subject-min-length=10
          - --subject-max-length=80
