name: Add Welcome Comment And Set PR Assignee
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  add-welcome-comment-set-assignee:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run add welcome comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
          GITHUB_EVENT_ACTION: ${{github.event.action}}
          GITHUB_EVENT_NAME: ${{github.event_name}}
          ACTION: "add-welcome-comment-set-assignee"
        run: uv run python .github/workflows/scripts/pr_workflow.py
