name: Cherry Pick On Comment
on:
  issue_comment:
    types: [created]
jobs:
  cherry-pick:
    name: Cherry Pick
    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, '/cherry-pick') &&
      ((github.event.pull_request.author_association != 'NONE') &&
      (github.event.pull_request.author_association != 'MANNEQUIN') &&
      (github.event.pull_request.author_association != 'FIRST_TIMER') &&
      (github.event.pull_request.author_association != 'FIRST_TIME_CONTRIBUTOR'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.RHODS_CI_BOT_PAT }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Cherry Pick
        uses:  dbasunag/cherry-pick-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.RHODS_CI_BOT_PAT }}
