name: Build container using the PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{github.event.pull_request.number}}
      cancel-in-progress: true

    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run make build
        run: make build
